---
title: IADB Survey of WSS suppliers in Brazil 2018/2019
date: " `r format(Sys.time(), '%B %e, %Y')` "
draft: false
# toc: true
type: docs
linktitle: IADB_WSS-Survey-Brazil 
menu:
  project:
    parent: Projects
    weight: 2
---

{{% alert warning %}}
Please note, the survey is still in progress, hence the results are subject to change and NOT (yet) ready for dissemination. 
{{% /alert %}}


## Link to Project Page 

https://lulliter.github.io/BrazilWaterSurvey/


## Purpose of the study 
The survey is part of a larger effort to collect original data in preparation of the publication “Development in America” 2020 that will focus on Infrastructure (Energy, Water and Transportation) sector in LAC.

## Creators
This page was created by Luisa M. Mimmi (Research Fellow - consultant at IADB) but builds on data collected by various IADB colleagues and partner organizations.  

## ACKNOWLEDGMENTS
+ This survey is sponsored by the **Interamerican Development Bank (IADB)**, Water Division, Knowledge Team  [WSA Knowledge](https://idbg.sharepoint.com/sites/WSAknowledge), where I work as a consultant. 

+ This survey has been implemented in the field by the is sponsored by the company **PoPa Research**, [website](http://www.poparesearch.com/) in partnership with IADB. 

+ For the structure of this static webpage, I followed the example of Prof Andrew Heiss [project page](https://stats.andrewheiss.com/donors-ngo-restrictions/index.html) who graciously shares his research work (with code).

### CONTACT
Feel free to contact me for questions and/or suggestions (lmm76@georgetown.edu or lmmimmi@iadb.org)  

